### ISSUE TITLE
订阅源错误提示

### ISSUE THREAD

**Issue by Robs87** [cn-kali-team/notion-rss#11]
![image](https://user-images.githubusercontent.com/90772605/230839119-8c9a30b3-d874-455c-b457-7905000ba66b.png)

订阅源提示“unable to parse feed: no root element”和“unable to parse JSON: missing field `version` at line 1 column 84”是什么意思呀？

**Comment by cn-kali-team** [comment]
可能订阅源返回的格式不是标准的，或者站点存在web防火墙，对你的请求拦截了，返回的不是一个xml文件
